### ISSUE TITLE
Extract what content is already living in the nixos manual here

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/release-wiki#1]
What it says on the tin.

**Comment by jonringer** [comment]
I'll do that, as part of https://github.com/NixOS/nixpkgs/issues/97405

**Comment by worldofpeace** [comment]
Oops, I already started since I had some time. See the current repo state.

**Comment by jonringer** [comment]
all good, I'll just make sure to follow through, including what's mentioned in the other issue :)

**Comment by dasJ** [comment]
Is this done? I can't find anything in the manual anymore
