### ISSUE TITLE
NixOS end-of-life instructions

### ISSUE THREAD

**Issue by roberth** [NixOS/release-wiki#31]
I was expecting to find instructions for what to do when a NixOS release becomes unsupported.
I'd like to add instructions to update `oldestSupportedRelease` on `master`, which is a new value in https://github.com/NixOS/nixpkgs/pull/163451. It improves the regular deprecation process.

**Comment by jonringer** [comment]
The only item is https://github.com/NixOS/release-wiki/blob/master/src/Release-Process-Walkthrough.md#a-month-after-release so far.

The linked PR looks more like nixos module change, rather than a consistent per-release step though.

**Comment by roberth** [comment]
Thanks! I've created #32 to support that the nixpkgs PR.

> The linked PR looks more like nixos module change, rather than a consistent per-release step though.

It does. The logic and docs are all about option renames, but it makes use of a variable that needs to be updated when the oldest release goes EOL, as that is the right time to start migrating out-of-tree modules.
