### ISSUE TITLE
Tag name is dangerous

### ISSUE THREAD

**Issue by roberth** [NixOS/release-wiki#45]
```nix
{
  inputs.nixpkgs.url = "NixOS/nixpkgs/22.05";
}
```

Did you spot the security issue?

Let's replace the release tags by something descriptive, like `22.05-start` or `22.05.0`, so that users don't accidentally fail to update their packages.

**Comment by dasJ** [comment]
While I agree with the point in general, this particular example feels like a niv bug.
I wouldn't expect `--branch` to use a tag.

**Comment by roberth** [comment]
> this particular example feels like a niv bug.

That's fair actually. I figured I'd add a non-flake example, but this is not it. Editing.

**Comment by bbenne10** [comment]
It isn't clear to me how `branch-off-XX.YY` (or `XX.YY` if the instructions are not followed closely) and `release-XX.YY` are meaningfully (and notably: publicly) different. The distinction between those two tags seem entirely *locally* useful for the release manager.

This very much feels like "release-XX.YY" or "XX.YY-release" (or "-initial" or something) could subsume the tag created here entirely (if maybe requiring a bit more care for the release manager, but that's what tooling is for imo). 

I guess the question I am asking is "What is the point of this tag being publicly pushed in the first place?"
