### ISSUE TITLE
Merge the contents of this repository into the NixOS manual

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/release-wiki#46]
Release management is part of NixOS development process, and should be documented in a central place: the NixOS manual.

Background: The Nix ecosystem is notoriously fragmented and hard to navigate. Please let us improve this step by step.

**Comment by mweinelt** [comment]
This documentation is only interesting for a narrow set of people and having it in this compact format in a dedicated repository makes it more palatable to the release managers and possible interested parties. It also allows us to iterate fast on it, by primarily consulting between the release manager team. That's not to say that we don't value external input, but the communication flow between the release managers during the release process is alot more intensive anyway.

So I'm not exactly convinced that this fragmentation is bad in this case.

**Comment by fricklerhandwerk** [comment]
> palatable to the release managers and possible interested parties

Right now, interested parties cannot even find this repository, except by pure chance.
The link to the release process on the [team's page on nixos.org](https://nixos.org/community/teams/nixos-release.html) is stale.

It doesn't have to be the manual. But it may make sense to move it closer to the source, because it's closely tied to what's happening there. We're in the process of doing that for the Nix team and the Documentation team.

Also, @lucperkins is working on porting [NixOS/nixos-homepage](https://github.com/NixOS/nixos-homepage/ ) to something more palatable. @mweinelt Do you think it would make sense _eventually_ moving information related to team processes there, such that it can be managed and accessed centrally?

I really only care about this because I'm trying to make all the teams' work more visible and discoverable.

**Comment by jonringer** [comment]
I would much rather have just a stub which refers to the rendered markdown book for the release wiki.

Being able to have a low bar to modification helps release managers keep wiki maintenance not being a burden.

Also, I don't think the release wiki is really valuable for most users; only use case I can think of is if an external party wants to inspect the release process, but I think it's easy enough to find. For me, the rendered markdown is the second link when searching "NixOS release process"

**Comment by jonringer** [comment]
> Right now, interested parties cannot even find this repository, except by pure chance.
The link to the release process on the [team's page on nixos.org](https://nixos.org/community/teams/nixos-release.html) is stale.

Yea, we should update that

**Comment by jonringer** [comment]
PR to update link: [Update link from it used to be located on the release manual in nixpkgs to the current rendered release wiki markdown repo.](https://github.com/NixOS/nixos-homepage/pull/960)

**Comment by dasJ** [comment]
Looks like this is done now
