### ISSUE TITLE
Hydra chapter

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/release-wiki#5]
Notably, that RMs should have hydra accounts with the ability to modify jobset configuration and to create jobsets.
The only thing they should really be doing is setting `stableBranch`. The actual creating of release jobsets is probably better suited for a infra team member.

**Comment by jonringer** [comment]
also, it would be nice if this process was documented a bit better so that the communication between the two teams is better understood.

But it is a pain needing to get in contact with someone and they aren't available, or there's no established way to contact them.

**Comment by worldofpeace** [comment]
> also, it would be nice if this process was documented a bit better so that the communication between the two teams is better understood.
> 
> But it is a pain needing to get in contact with someone and they aren't available, or there's no established way to contact them.

Exactly, that was a minor issue this release because we didn't do any formal scheduling. I think if: 
* team discussions could be enabled for a team on github for people with access
* we schedule a time with someone to have the jobsets ready
* can that be done before hand (not all at once/same day?) that would be preferable
* we have good access to hydra to switch stableBranch and do that days before the slated release date

**Comment by jonringer** [comment]
I think at the very least, when I'm converting the release process over the new wiki, I'll better convey how and when certain items should be done
